export const USER_LOGIN = 'USER_LOGIN';
export const USER_LOGOUT = 'USER_LOGOUT';
export const USER_CHECK_BOOKMARK = 'USER_CHECK_BOOKMARK';
export const USER_ADD_BOOKMARK = 'USER_ADD_BOOKMARK';
export const USER_REMOVE_BOOKMARK = 'USER_REMOVE_BOOKMARK';

export const GET_NOVEL_BY_ID = 'GET_NOVEL_BY_ID';
export const GET_CHAPTER_BY_NOVELID_CHAPTERNO =
  'GET_CHAPTER_BY_NOVELID_CHAPTERNO';
